# Generated by Django 6.0.6 on 2026-06-27 18:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Headquarter Admin'), ('district_admin', 'District Admin'), ('Station_admin', 'Station Commander/OC'), ('officer', 'Police Officer')], default='officer', max_length=25)),
                ('rank', models.CharField(blank=True, choices=[('PC', 'Police Constale '), ('SPC', 'Special Police Constable'), ('CPL', 'Corporal'), ('SGT', 'Sergent'), ('SSGT', 'Staff Sergent'), ('SSGTM', 'Senior Staff Sergent'), ('INSP', 'Inspector of Police'), ('ASP', 'Assistant Superintendent of Police'), ('SP', 'Superintendent of Police'), ('SSP', 'Senior Superintendent of Police'), ('CP', 'Commissioner of Police'), ('ACP', 'Assistant Commissioner of police'), ('DCP', 'Deputy Commissioner of Police'), ('IGP', 'Inspector General of Police')], max_length=50, null=True)),
                ('force_number', models.CharField(blank=True, help_text='For Junior OfficerS: UPF/YY/XXXXXX', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Force Number format: UPF/YY/XXXXXX (e.g., UPF/26/000012)', regex='^UPF/\\d{2}/\\d{6}$')])),
                ('file_number', models.CharField(blank=True, help_text='For Senior Officers: INITIALS/YYYY/NO', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='File Number format: XX/YYYY/NNN (e.g., OG/2026/001)', regex='^[A-Z]{2,3}/\\d{4}/\\d{3}$')])),
                ('badge_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('biometric_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined_force', models.DateField(blank=True, null=True)),
                ('nin', models.CharField(blank=True, max_length=15, null=True)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('is_active_officer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Officer Profile',
                'verbose_name_plural': 'Officer Profiles',
                'ordering': ['-rank', 'force_number'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('headquarters_location', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regional_commander', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_region', to='core.profile')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_commander', models.ForeignKey(blank=True, limit_choices_to={'role': 'district_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_district', to='core.profile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.region')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('station_code', models.CharField(max_length=25, unique=True)),
                ('station_type', models.CharField(choices=[('headquarters', 'Police Headquarters'), ('division', 'Division Police Station'), ('station', 'Police Station'), ('post', 'Police Post'), ('special', 'Special Unit')], default='station', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('physical_address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_24_hours', models.BooleanField(default=True)),
                ('has_detention', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.district')),
                ('station_commander', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['station_admin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_station', to='core.profile')),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_officers', to='core.station'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Uganda phone number', regex='^\\+?256\\d{9}$|^0\\d{9}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_user_groups', related_query_name='core_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_permissions', related_query_name='core_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'name'], name='core_distri_region__b41e25_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['code'], name='core_distri_code_ea49e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['station_code'], name='core_statio_station_ab5864_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['district', 'is_active'], name='core_statio_distric_1feb89_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['force_number'], name='core_profil_force_n_1c94a7_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['file_number'], name='core_profil_file_nu_053b22_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'rank'], name='core_profil_role_49d4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['current_station'], name='core_profil_current_66b029_idx'),
        ),
    ]
