# Generated by Django 6.0.6 on 2026-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Headquarter Admin'), ('regional_admin', 'Regional Commander'), ('district_admin', 'District Admin'), ('Station_admin', 'Station Commander/OC'), ('officer', 'Police Officer')], default='officer', max_length=25),
        ),
    ]
