# Generated by Django 6.0.6 on 2026-07-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badge_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='biometric_id',
        ),
    ]
