# Generated by Django 6.0.6 on 2026-07-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_badge_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='district',
            name='core_distri_code_ea49e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='station',
            name='core_statio_station_ab5864_idx',
        ),
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, choices=[('SPC', 'Special Police Constable'), ('PPC', 'Probationer Police Constale '), ('PC', 'Police Constale '), ('CPL', 'Corporal'), ('SGT', 'Sergent'), ('SSGT', 'Station Sergent'), ('HC', 'Head Constable'), ('HCM', 'Head Constable Major'), ('LAIP', 'Learner Assitant Inspector of Police'), ('AIP', 'Assitant Inspector of Police'), ('IP', 'Inspector Police'), ('CASP', 'Cadet Assistant Superintendent of Police'), ('ASP', 'Assistant Superintendent of Police'), ('SP', 'Superintendent of Police'), ('SSP', 'Senior Superintendent of Police'), ('ACP', 'Assistant Commissioner of police'), ('CP', 'Commissioner of Police'), ('AIGP', 'Assistant Inspector General of Police'), ('IGP', 'Inspector General of Police')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='capacity',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('headquarters', 'Police Headquarters'), ('division', 'Division Police Station'), ('station', 'Police Station'), ('post', 'Police Post'), ('detach', 'Detach')], default='station', max_length=20),
        ),
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_code',
        ),
    ]
