# Generated by Django 6.0.6 on 2026-07-04 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_district_core_distri_code_ea49e0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_force_number_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_force_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file_number',
            field=models.CharField(blank=True, help_text='For Senior Officers (LAIP+): First letter of surname + 4 digits, e.g., A0001', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='File Number format: Letter + 4 digits (e.g., A0001)', regex='^[A-Z]\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='force_number',
            field=models.CharField(blank=True, help_text='For Junior Officers (SPC-HCM): Digits only, e.g., 91765', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Force Number must be digits only (e.g., 91765)', regex='^\\d{4,6}$')]),
        ),
    ]
