# Generated by Django 6.0.6 on 2026-06-27 18:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated: UPF/OCC/STATION/YYYY/MM/XXXXX', max_length=30, unique=True)),
                ('reporter_full_name', models.CharField(max_length=250)),
                ('reporter_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('reporter_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('reporter_tribe', models.CharField(max_length=50)),
                ('reporter_occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('reporter_residence', models.TextField()),
                ('reporter_contact', models.CharField(blank=True, max_length=13, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('what_happened', models.TextField()),
                ('when_it_happened', models.DateTimeField()),
                ('where_it_happened', models.TextField()),
                ('who_was_involved', models.TextField(help_text='Describe victims, suspects, and witnesses')),
                ('why_it_happened', models.TextField(blank=True, help_text='Motive or cause if known')),
                ('how_it_happened', models.TextField(help_text='Method, means, or weapons used')),
                ('crime_type', models.CharField(choices=[('THEFT', 'Theft'), ('ROBBERY', 'Aggravated Robbery'), ('BURGLARY', 'Burglary/Breaking'), ('ASSAULT', 'Assault'), ('ASSAULT_AGG', 'Aggravated Assault'), ('DOMESTIC', 'Domestic Violence'), ('RAPE', 'Rape'), ('DEFILEMENT', 'Defilement'), ('HOMICIDE', 'Homicide/Murder'), ('MANSLAUGHTER', 'Manslaughter'), ('KIDNAP', 'Kidnapping'), ('FRAUD', 'Fraud'), ('FORGERY', 'Forgery'), ('DRUGS', 'Narcotics/Drugs'), ('TRAFFIC', 'Traffic Offense'), ('CYBER', 'Cyber Crime'), ('CORRUPTION', 'Corruption'), ('TERRORISM', 'Terrorism'), ('OTHER', 'Other Criminal Offense')], max_length=50)),
                ('case_status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('PENDING', 'Pending Further Info'), ('SUSPECT_NAMED', 'Suspect Named'), ('SUSPECT_ARRESTED', 'Suspect Arrested'), ('FORWARDED_DPP', 'Forwarded to DPP'), ('COURT', 'In Court'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted'), ('CLOSED', 'Closed'), ('APPEALED', 'Under Appeal'), ('REFERRED', 'Referred to Other Unit')], default='OPEN', max_length=50, verbose_name='Case Status')),
                ('crime_scene_location', models.CharField(blank=True, max_length=255, verbose_name='Crime Scene Location')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Involves minors, sexual offenses, or security matters', verbose_name='Sensitive Case')),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Reported')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('investigating_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigating_cases', to='core.profile', verbose_name='Investigating Officer')),
                ('reporting_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to='core.profile', verbose_name='Reporting Officer')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='core.station', verbose_name='Police Station')),
            ],
            options={
                'verbose_name': 'Occurrence/Case',
                'verbose_name_plural': 'Occurrences/Cases',
                'ordering': ['-date_reported'],
                'permissions': [('view_sensitive_case', 'Can view sensitive cases'), ('update_case_status', 'Can update case status'), ('assign_investigator', 'Can assign investigating officer')],
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibit_type', models.CharField(choices=[('WEAPON', 'Weapon'), ('DOCUMENT', 'Document'), ('DIGITAL', 'Digital Evidence'), ('BIOLOGICAL', 'Biological Sample'), ('PHOTO', 'Photograph'), ('VIDEO', 'Video Recording'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('exhibit_number', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('storage_location', models.CharField(max_length=200)),
                ('chain_of_custody', models.TextField(blank=True, help_text='Record of everyone who handled this exhibit')),
                ('is_returned', models.BooleanField(default=False)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_exhibits', to='core.profile')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='occurrence.occurrence')),
            ],
            options={
                'verbose_name': 'Exhibit',
                'verbose_name_plural': 'Exhibits',
                'ordering': ['-date_collected'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('PENDING', 'Pending Further Info'), ('SUSPECT_NAMED', 'Suspect Named'), ('SUSPECT_ARRESTED', 'Suspect Arrested'), ('FORWARDED_DPP', 'Forwarded to DPP'), ('COURT', 'In Court'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted'), ('CLOSED', 'Closed'), ('APPEALED', 'Under Appeal'), ('REFERRED', 'Referred to Other Unit')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('PENDING', 'Pending Further Info'), ('SUSPECT_NAMED', 'Suspect Named'), ('SUSPECT_ARRESTED', 'Suspect Arrested'), ('FORWARDED_DPP', 'Forwarded to DPP'), ('COURT', 'In Court'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted'), ('CLOSED', 'Closed'), ('APPEALED', 'Under Appeal'), ('REFERRED', 'Referred to Other Unit')], max_length=20)),
                ('update_text', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to='core.profile')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='occurrence.occurrence')),
            ],
            options={
                'verbose_name': 'Case Update',
                'verbose_name_plural': 'Case Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTrackingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(editable=False, help_text='8-character code for citizen access', max_length=12, unique=True)),
                ('reporter_phone', models.CharField(max_length=15)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_access', to='occurrence.occurrence')),
            ],
            options={
                'verbose_name': 'Case Tracking Access',
                'verbose_name_plural': 'Case Tracking Access Records',
            },
        ),
        migrations.CreateModel(
            name='PublicCaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='occurrence.casetrackingaccess')),
            ],
            options={
                'verbose_name': 'Public Comment',
                'verbose_name_plural': 'Public Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoliceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('is_visible_to_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_response', to='occurrence.publiccasecomment')),
            ],
            options={
                'verbose_name': 'Police Response',
                'verbose_name_plural': 'Police Responses',
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('contact', models.CharField(max_length=13)),
                ('residence', models.TextField()),
                ('relationship_to_case', models.CharField(blank=True, help_text='e.g., Eyewitness, Neighbor, Relative', max_length=50)),
                ('statement', models.TextField()),
                ('statement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_protected', models.BooleanField(default=False, help_text='Mark if witness requires protection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='occurrence.occurrence')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_statements', to='core.profile')),
            ],
            options={
                'verbose_name': 'Witness',
                'verbose_name_plural': 'Witnesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['reference_number'], name='occurrence__referen_03af14_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['case_status'], name='occurrence__case_st_49be46_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['crime_type'], name='occurrence__crime_t_7d6d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['date_reported'], name='occurrence__date_re_f5fbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['station', 'case_status'], name='occurrence__station_34c5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['occurrence', '-created_at'], name='occurrence__occurre_1c9854_idx'),
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['new_status'], name='occurrence__new_sta_725678_idx'),
        ),
        migrations.AddIndex(
            model_name='casetrackingaccess',
            index=models.Index(fields=['access_code'], name='occurrence__access__0bb685_idx'),
        ),
        migrations.AddIndex(
            model_name='casetrackingaccess',
            index=models.Index(fields=['occurrence'], name='occurrence__occurre_3a8e4a_idx'),
        ),
    ]
