# Generated by Django 6.0.6 on 2026-07-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseupdate',
            name='new_status',
            field=models.CharField(choices=[('Under_Inquiry', 'Under Inquiry'), ('COURT', 'Submitted to Court/RSA'), ('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('CLOSED', 'Closed/Put away')], max_length=20),
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Under_Inquiry', 'Under Inquiry'), ('COURT', 'Submitted to Court/RSA'), ('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('CLOSED', 'Closed/Put away')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='case_status',
            field=models.CharField(choices=[('Under_Inquiry', 'Under Inquiry'), ('COURT', 'Submitted to Court/RSA'), ('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('CLOSED', 'Closed/Put away')], default='OPEN', max_length=50, verbose_name='Case Status'),
        ),
    ]
