# Generated by Django 6.0.6 on 2026-06-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.profile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.station'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to='core.profile'),
        ),
        migrations.AddField(
            model_name='dutyroster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rosters', to='core.profile'),
        ),
        migrations.AddField(
            model_name='dutyroster',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='core.profile'),
        ),
        migrations.AddField(
            model_name='dutyroster',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='core.station'),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='core.profile'),
        ),
        migrations.AddField(
            model_name='leave',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.profile'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['profile', 'date'], name='attendance__profile_eaec26_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['station', 'date'], name='attendance__station_c82039_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['check_in_time'], name='attendance__check_i_377917_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('profile', 'date')},
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['station', 'date'], name='attendance__station_1dd068_idx'),
        ),
        migrations.AddIndex(
            model_name='dutyroster',
            index=models.Index(fields=['profile', 'date'], name='attendance__profile_90062b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyroster',
            unique_together={('profile', 'date', 'shift')},
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['profile', 'status'], name='attendance__profile_f80e40_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_a9aa8f_idx'),
        ),
    ]
