# Generated by Django 6.0.6 on 2026-07-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyroster',
            name='shift',
            field=models.CharField(choices=[('NIGHT', 'Night Shift (18:00-06:00)'), ('DAY', 'Day Duty (06:00-18:00)'), ('SPECIAL', 'Special Duty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('Passleave', 'Pass Leave'), ('STUDY', 'Study Leave'), ('AWOL', 'AWOL'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
